using System.ComponentModel.DataAnnotations;

namespace ISysLab2023.Backend.Lib.Domain.Person;

/// <summary>
/// The class is a basic description of a person.
/// </summary>
public class BasePerson
{
    /// <summary>
    /// Autogenerated primary key in string format. 
    /// Represents Guid
    /// </summary>
    [Required]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// Name of the person
    /// </summary>
    public string? Name { get; set; }
    /// <summary>
    /// Surname of the person
    /// </summary>
    public string? Surname { get; set; }
    /// <summary>
    /// Patronymic of the person
    /// </summary>
    public string? Patronymic { get; set; }

    /// <summary>
    /// Birthday. Format DD.MM.YYYY
    /// </summary>
    public DateOnly? BirthDay { get; set; }

    /// <summary>
    /// Email. Format lalala@lala.la
    /// </summary>
    [RegularExpression(@"^[^@\s]+@[^@\s]+\.[^@\s]+$")]
    public string? Email { get; set; }

    /// <summary>
    /// Phone. Format @[0-9]{11}
    /// </summary>
    [RegularExpression(@"[0-9]{10}")]
    public string? Phone { get; set; }
}
