using ISysLab2023.Backend.Lib.Domain.SupportClasses;
using System.ComponentModel.DataAnnotations;

namespace ISysLab2023.Backend.Lib.Domain.WorkingProjects;

/// <summary>
/// Working project
/// </summary>
public class Project
{
    /// <summary>
    /// Autogenerated primary key in string format. Represents Guid
    /// </summary>
    [Required]
    public Guid Id { get; set; } = new();

    /// <summary>
    /// Name of department
    /// </summary>
    public string Title { get; set; } = String.Empty;

    /// <summary>
    /// Project code
    /// </summary>
    public string ProjectCode { get; set; } = String.Empty;

    /// <summary>
    /// A field that implements a many-to-many relationship with the Employee class
    /// </summary>
    public ICollection<EmployeeProjects>? EmployeeProjects { get; set; } = new List<EmployeeProjects>();
}
